# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import number_pb2 as number__pb2


class NumberStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendNumber = channel.unary_unary(
                '/number.Number/SendNumber',
                request_serializer=number__pb2.NumberRequest.SerializeToString,
                response_deserializer=number__pb2.MaxNumberResponse.FromString,
                )


class NumberServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SendNumber(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NumberServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendNumber': grpc.unary_unary_rpc_method_handler(
                    servicer.SendNumber,
                    request_deserializer=number__pb2.NumberRequest.FromString,
                    response_serializer=number__pb2.MaxNumberResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'number.Number', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Number(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SendNumber(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/number.Number/SendNumber',
            number__pb2.NumberRequest.SerializeToString,
            number__pb2.MaxNumberResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
