# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: number.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cnumber.proto\x12\x06number\"\x1f\n\rNumberRequest\x12\x0e\n\x06number\x18\x01 \x01(\x05\"\'\n\x11MaxNumberResponse\x12\x12\n\nmax_number\x18\x01 \x01(\x05\x32J\n\x06Number\x12@\n\nSendNumber\x12\x15.number.NumberRequest\x1a\x19.number.MaxNumberResponse\"\x00\x42\x10Z\x0e\x62uffers/numberb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'number_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\016buffers/number'
  _globals['_NUMBERREQUEST']._serialized_start=24
  _globals['_NUMBERREQUEST']._serialized_end=55
  _globals['_MAXNUMBERRESPONSE']._serialized_start=57
  _globals['_MAXNUMBERRESPONSE']._serialized_end=96
  _globals['_NUMBER']._serialized_start=98
  _globals['_NUMBER']._serialized_end=172
# @@protoc_insertion_point(module_scope)
